// 여행·일상 영어 190표현 — 공항 / 숙소 / 교통 / 식당 / 쇼핑 / 관광 / 문제상황 / 대화 / 건강 / 일상
// 단어뿐 아니라 실제로 입에서 바로 나와야 하는 표현 덩어리(check in, run out of…)를 함께 담았다.
// ex 의 "___" 자리에 w 가 원형 그대로 들어간다.
const WORDS = [
  /* ===== 공항 · 기내 ===== */
  { w:"check in",          pos:"phr", ko:"탑승 수속을 하다",       cat:"air",  ex:"I need to ___ for my flight to Bangkok.",              exKo:"방콕행 비행기 탑승 수속을 해야 해요." },
  { w:"boarding pass",     pos:"n",   ko:"탑승권",                cat:"air",  ex:"Please have your ___ ready at the gate.",              exKo:"게이트에서 탑승권을 준비해 주세요." },
  { w:"carry-on",          pos:"n",   ko:"기내 반입 가방",         cat:"air",  ex:"Is this bag small enough as a ___ ?",                  exKo:"이 가방 기내에 들고 탈 수 있는 크기인가요?" },
  { w:"baggage claim",     pos:"n",   ko:"수하물 찾는 곳",         cat:"air",  ex:"Where is the ___ for flight KE12?",                    exKo:"KE12편 수하물은 어디서 찾나요?" },
  { w:"aisle seat",        pos:"n",   ko:"통로 쪽 좌석",           cat:"air",  ex:"Could I get an ___ , please?",                         exKo:"통로 쪽 좌석으로 주실 수 있나요?" },
  { w:"window seat",       pos:"n",   ko:"창가 쪽 좌석",           cat:"air",  ex:"I'd prefer a ___ if there's one left.",                exKo:"남아 있다면 창가 쪽이 좋아요." },
  { w:"layover",           pos:"n",   ko:"경유 대기 시간",         cat:"air",  ex:"I have a six-hour ___ in Dubai.",                      exKo:"두바이에서 6시간 경유 대기가 있어요." },
  { w:"connecting flight", pos:"n",   ko:"연결 항공편",            cat:"air",  ex:"Will I make my ___ if we land late?",                  exKo:"늦게 착륙하면 연결 항공편을 탈 수 있을까요?" },
  { w:"delayed",           pos:"adj", ko:"지연된",                cat:"air",  ex:"Our flight is ___ by two hours.",                      exKo:"우리 항공편이 두 시간 지연됐어요." },
  { w:"board",             pos:"v",   ko:"탑승하다",              cat:"air",  ex:"We start to ___ in about twenty minutes.",             exKo:"20분쯤 후에 탑승을 시작합니다." },
  { w:"take off",          pos:"phr", ko:"이륙하다",              cat:"air",  ex:"The plane will ___ as soon as the weather clears.",    exKo:"날씨가 개는 대로 비행기가 이륙할 거예요." },
  { w:"land",              pos:"v",   ko:"착륙하다",              cat:"air",  ex:"We should ___ around nine in the morning.",            exKo:"아침 9시쯤 착륙할 예정이에요." },
  { w:"customs",           pos:"n",   ko:"세관",                  cat:"air",  ex:"You'll go through ___ after picking up your bags.",    exKo:"짐을 찾은 뒤 세관을 통과하게 됩니다." },
  { w:"immigration",       pos:"n",   ko:"출입국 심사",            cat:"air",  ex:"The line at ___ was really long.",                     exKo:"입국 심사 줄이 정말 길었어요." },
  { w:"declare",           pos:"v",   ko:"(세관에) 신고하다",      cat:"air",  ex:"Do I need to ___ this bottle of wine?",                exKo:"이 와인은 신고해야 하나요?" },
  { w:"jet lag",           pos:"n",   ko:"시차 피로",             cat:"air",  ex:"I always get bad ___ flying east.",                    exKo:"동쪽으로 갈 때는 시차 적응이 늘 힘들어요." },
  { w:"overhead bin",      pos:"n",   ko:"기내 머리 위 짐칸",      cat:"air",  ex:"Could you help me put this in the ___ ?",              exKo:"이거 짐칸에 올리는 것 좀 도와주시겠어요?" },
  { w:"buckle up",         pos:"phr", ko:"안전벨트를 매다",        cat:"air",  ex:"Everyone needs to ___ before we go.",                  exKo:"출발 전에 다들 안전벨트 매야 해요." },
  { w:"gate",              pos:"n",   ko:"탑승구",                cat:"air",  ex:"They changed our ___ to B12.",                         exKo:"탑승구가 B12로 바뀌었어요." },
  { w:"one-way",           pos:"adj", ko:"편도의",                cat:"air",  ex:"I only need a ___ ticket.",                            exKo:"편도 표만 있으면 돼요." },
  { w:"round-trip",        pos:"adj", ko:"왕복의",                cat:"air",  ex:"A ___ ticket is cheaper than two singles.",            exKo:"왕복 표가 편도 두 장보다 싸요." },
  { w:"luggage",           pos:"n",   ko:"짐, 수하물",            cat:"air",  ex:"My ___ didn't come out on the belt.",                  exKo:"제 짐이 벨트에 안 나왔어요." },
  { w:"security",          pos:"n",   ko:"보안 검색",             cat:"air",  ex:"Take your laptop out before ___ .",                    exKo:"보안 검색 전에 노트북을 꺼내세요." },
  { w:"duty-free",         pos:"adj", ko:"면세의",                cat:"air",  ex:"I picked up some perfume at the ___ shop.",            exKo:"면세점에서 향수를 좀 샀어요." },
  { w:"overweight",        pos:"adj", ko:"중량 초과의",            cat:"air",  ex:"My suitcase was ___ , so I paid a fee.",               exKo:"가방이 중량 초과라 추가 요금을 냈어요." },

  /* ===== 숙소 ===== */
  { w:"check out",         pos:"phr", ko:"퇴실하다",              cat:"stay", ex:"What time do I have to ___ tomorrow?",                 exKo:"내일 몇 시에 퇴실해야 하나요?" },
  { w:"reservation",       pos:"n",   ko:"예약",                  cat:"stay", ex:"I have a ___ under the name Kim.",                     exKo:"김이라는 이름으로 예약했어요." },
  { w:"front desk",        pos:"n",   ko:"프런트",                cat:"stay", ex:"Just leave the key at the ___ .",                      exKo:"열쇠는 프런트에 맡기시면 돼요." },
  { w:"walk in",           pos:"phr", ko:"예약 없이 그냥 가다",     cat:"stay", ex:"Can we just ___ without a booking?",                  exKo:"예약 없이 그냥 가도 되나요?",  tip:"호텔·식당 다 통용. 반대는 You need a reservation." },
  { w:"fully booked",      pos:"phr", ko:"예약이 꽉 찬",           cat:"stay", ex:"Sorry, we're ___ tonight.",                          exKo:"죄송해요, 오늘 밤은 예약이 다 찼어요." },
  { w:"housekeeping",      pos:"n",   ko:"객실 청소 서비스",       cat:"stay", ex:"Could you send ___ up to my room?",                    exKo:"객실 청소를 보내 주시겠어요?" },
  { w:"wake-up call",      pos:"n",   ko:"모닝콜",                cat:"stay", ex:"Could I get a ___ at six thirty?",                     exKo:"6시 30분에 모닝콜 부탁드려도 될까요?" },
  { w:"luggage storage",   pos:"n",   ko:"짐 보관 서비스",         cat:"stay", ex:"Do you have ___ after checkout?",                      exKo:"체크아웃 후에 짐 보관이 되나요?" },
  { w:"deposit",           pos:"n",   ko:"보증금",                cat:"stay", ex:"They asked for a fifty-dollar ___ at check-in.",       exKo:"체크인할 때 50달러 보증금을 요구했어요." },
  { w:"air conditioning",  pos:"n",   ko:"에어컨",                cat:"stay", ex:"The ___ in my room isn't working.",                    exKo:"방 에어컨이 작동하지 않아요." },
  { w:"towel",             pos:"n",   ko:"수건",                  cat:"stay", ex:"Could I get another ___ , please?",                    exKo:"수건 하나만 더 주시겠어요?" },
  { w:"extend",            pos:"v",   ko:"(기간을) 연장하다",      cat:"stay", ex:"Can I ___ my stay by one more night?",                 exKo:"하루 더 연장할 수 있을까요?" },
  { w:"shuttle",           pos:"n",   ko:"셔틀버스",              cat:"stay", ex:"Is there a free ___ to the airport?",                  exKo:"공항까지 무료 셔틀이 있나요?" },
  { w:"lobby",             pos:"n",   ko:"로비",                  cat:"stay", ex:"I'll wait for you in the ___ .",                       exKo:"로비에서 기다릴게요." },
  { w:"book",              pos:"v",   ko:"예약하다",              cat:"stay", ex:"I'd like to ___ a room for two nights.",               exKo:"2박으로 방을 예약하고 싶어요." },
  { w:"cancel",            pos:"v",   ko:"취소하다",              cat:"stay", ex:"I need to ___ my booking for Friday.",                 exKo:"금요일 예약을 취소해야 해요." },
  { w:"available",         pos:"adj", ko:"이용 가능한",            cat:"stay", ex:"Is the room ___ from Monday?",                         exKo:"그 방 월요일부터 이용 가능한가요?" },
  { w:"included",          pos:"adj", ko:"포함된",                cat:"stay", ex:"Is breakfast ___ in the price?",                       exKo:"조식이 요금에 포함돼 있나요?" },
  { w:"noisy",             pos:"adj", ko:"시끄러운",              cat:"stay", ex:"The street outside is really ___ at night.",           exKo:"밤에 바깥 길이 정말 시끄러워요." },
  { w:"spacious",          pos:"adj", ko:"넓은",                  cat:"stay", ex:"Their apartment is surprisingly ___ .",                exKo:"그 집은 생각보다 훨씬 넓어요." },

  /* ===== 교통 · 길찾기 ===== */
  { w:"get around",        pos:"phr", ko:"돌아다니다, 이동하다",   cat:"move", ex:"What's the best way to ___ in this city?",             exKo:"이 도시에서 이동하기 가장 좋은 방법이 뭔가요?" },
  { w:"catch",             pos:"v",   ko:"(차·기차를) 타다",      cat:"move", ex:"Where can I ___ the bus to the old town?",             exKo:"구시가지 가는 버스는 어디서 타나요?" },
  { w:"get off",           pos:"phr", ko:"내리다",                cat:"move", ex:"Which stop should I ___ at for the museum?",           exKo:"박물관에 가려면 어느 정류장에서 내려야 하나요?" },
  { w:"transfer",          pos:"v",   ko:"환승하다",              cat:"move", ex:"You'll need to ___ at Central Station.",               exKo:"센트럴역에서 환승하셔야 해요." },
  { w:"fare",              pos:"n",   ko:"교통 요금",             cat:"move", ex:"How much is the ___ to the airport?",                  exKo:"공항까지 요금이 얼마인가요?" },
  { w:"platform",          pos:"n",   ko:"승강장",                cat:"move", ex:"The train leaves from ___ four.",                      exKo:"기차는 4번 승강장에서 출발해요." },
  { w:"run",               pos:"v",   ko:"(버스·기차가) 다니다",   cat:"move", ex:"How often do the buses ___ ?",                        exKo:"버스가 얼마나 자주 다녀요?" },
  { w:"rush hour",         pos:"n",   ko:"혼잡 시간대",            cat:"move", ex:"Avoid the subway during ___ .",                        exKo:"혼잡 시간대에는 지하철을 피하세요." },
  { w:"traffic",           pos:"n",   ko:"교통량, 차 막힘",        cat:"move", ex:"We got stuck in ___ for an hour.",                     exKo:"차가 막혀서 한 시간을 갇혀 있었어요." },
  { w:"pick up",           pos:"phr", ko:"태우러 오다, 찾아오다",  cat:"move", ex:"Can you ___ my friend at the airport?",                exKo:"공항에서 제 친구 좀 태워 오실 수 있나요?" },
  { w:"drop off",          pos:"phr", ko:"내려 주다, 갖다 주다",   cat:"move", ex:"Could you ___ my bags at the hotel first?",            exKo:"먼저 제 짐을 호텔에 내려 주시겠어요?" },
  { w:"walking distance",  pos:"n",   ko:"걸어갈 만한 거리",       cat:"move", ex:"The beach is within ___ .",                            exKo:"해변은 걸어갈 만한 거리예요." },
  { w:"head",              pos:"v",   ko:"(~쪽으로) 가다",        cat:"move", ex:"Just ___ straight for two blocks.",                    exKo:"두 블록만 곧장 가세요." },
  { w:"turn",              pos:"v",   ko:"돌다, 꺾다",            cat:"move", ex:"You'll ___ left at the traffic light.",                exKo:"신호등에서 좌회전하시면 돼요." },
  { w:"block",             pos:"n",   ko:"블록, 한 구획",          cat:"move", ex:"The bank is one ___ away.",                            exKo:"은행은 한 블록 떨어져 있어요." },
  { w:"light",             pos:"n",   ko:"신호등",                cat:"move", ex:"Turn left at the ___ .",                               exKo:"신호등에서 좌회전하세요.",     tip:"traffic light를 말할 땐 보통 그냥 the light." },
  { w:"detour",            pos:"n",   ko:"우회로",                cat:"move", ex:"There's a ___ because of road work.",                  exKo:"도로 공사 때문에 우회로가 있어요." },
  { w:"ride",              pos:"n",   ko:"타고 가는 시간·거리",    cat:"move", ex:"It's a twenty-minute ___ from here.",                  exKo:"여기서 20분 정도 타고 가면 돼요." },
  { w:"car rental",        pos:"n",   ko:"렌터카",                cat:"move", ex:"We booked a ___ for three days.",                      exKo:"3일 동안 렌터카를 예약했어요." },
  { w:"license",           pos:"n",   ko:"면허증",                cat:"move", ex:"You'll need an international driving ___ .",           exKo:"국제 운전 면허증이 필요할 거예요." },
  { w:"parking lot",       pos:"n",   ko:"주차장",                cat:"move", ex:"There's a free ___ behind the building.",              exKo:"건물 뒤에 무료 주차장이 있어요." },
  { w:"crowded",           pos:"adj", ko:"붐비는",                cat:"move", ex:"The last train is always ___ .",                       exKo:"막차는 항상 붐벼요." },
  { w:"on foot",           pos:"phr", ko:"걸어서",                cat:"move", ex:"We explored the whole town ___ .",                     exKo:"우리는 마을 전체를 걸어서 둘러봤어요." },
  { w:"lost",              pos:"adj", ko:"길을 잃은",             cat:"move", ex:"I think we're ___ — let me check the map.",            exKo:"우리 길을 잃은 것 같아요. 지도 좀 볼게요." },
  { w:"shortcut",          pos:"n",   ko:"지름길",                cat:"move", ex:"The driver took a ___ through the back streets.",      exKo:"기사님이 뒷길로 지름길을 탔어요." },

  /* ===== 식당 · 카페 ===== */
  { w:"order",             pos:"v",   ko:"주문하다",              cat:"food", ex:"Are you ready to ___ ?",                               exKo:"주문하시겠어요?" },
  { w:"recommend",         pos:"v",   ko:"추천하다",              cat:"food", ex:"What would you ___ here?",                            exKo:"여기서 뭘 추천하시나요?" },
  { w:"known for",         pos:"phr", ko:"~로 유명한",             cat:"food", ex:"What is this place ___ ?",                            exKo:"이 집은 뭐로 유명해요?",       tip:"메뉴판 단어 specialty보다 말할 때 훨씬 자주 씀." },
  { w:"starter",           pos:"n",   ko:"전채, 애피타이저",       cat:"food", ex:"We'll share a ___ first.",                             exKo:"먼저 전채를 하나 나눠 먹을게요." },
  { w:"main course",       pos:"n",   ko:"메인 요리",             cat:"food", ex:"What are you having for your ___ ?",                   exKo:"메인 요리는 뭘로 하실 거예요?" },
  { w:"side dish",         pos:"n",   ko:"곁들임 요리",            cat:"food", ex:"Can I get a ___ of fries with that?",                  exKo:"거기에 감자튀김도 곁들여 주실 수 있나요?" },
  { w:"to go",             pos:"phr", ko:"포장해서",              cat:"food", ex:"I'll have a large coffee ___ , please.",               exKo:"큰 사이즈 커피 포장으로 주세요." },
  { w:"for here",          pos:"phr", ko:"매장에서 먹을",          cat:"food", ex:"Is that ___ or to go?",                                exKo:"드시고 가시나요, 포장이신가요?" },
  { w:"refill",            pos:"n",   ko:"리필",                  cat:"food", ex:"Do you offer a free ___ ?",                            exKo:"무료 리필이 되나요?" },
  { w:"bill",              pos:"n",   ko:"계산서",                cat:"food", ex:"Could we get the ___ , please?",                       exKo:"계산서 좀 주시겠어요?" },
  { w:"split the bill",    pos:"phr", ko:"각자 계산하다",          cat:"food", ex:"Do you mind if we ___ ?",                              exKo:"각자 계산해도 괜찮을까요?" },
  { w:"tip",               pos:"n",   ko:"팁",                    cat:"food", ex:"Is a ___ expected at restaurants here?",               exKo:"여기 식당에서는 팁을 주는 게 보통인가요?" },
  { w:"spicy",             pos:"adj", ko:"매운",                  cat:"food", ex:"Is this dish very ___ ?",                              exKo:"이 요리 많이 매운가요?" },
  { w:"allergic",          pos:"adj", ko:"알레르기가 있는",        cat:"food", ex:"I'm ___ to peanuts.",                                  exKo:"저는 땅콩 알레르기가 있어요." },
  { w:"vegetarian",        pos:"adj", ko:"채식의",                cat:"food", ex:"Do you have any ___ options?",                         exKo:"채식 메뉴가 있나요?" },
  { w:"medium rare",       pos:"phr", ko:"(스테이크) 미디엄 레어", cat:"food", ex:"I'd like my steak ___ .",                              exKo:"스테이크는 미디엄 레어로 해 주세요." },
  { w:"leftovers",         pos:"n",   ko:"남은 음식",             cat:"food", ex:"Could I get a box for the ___ ?",                      exKo:"남은 음식 포장 용기를 주시겠어요?" },
  { w:"table for two",     pos:"n",   ko:"2인용 테이블",           cat:"food", ex:"Do you have a ___ available?",                         exKo:"2인 테이블 자리 있나요?" },
  { w:"tap water",         pos:"n",   ko:"(그냥) 물, 수돗물",      cat:"food", ex:"Could we get some ___ , please?",                      exKo:"물 좀 주시겠어요?" },
  { w:"thirsty",           pos:"adj", ko:"목마른",                cat:"food", ex:"I'm so ___ after that hike.",                          exKo:"등산하고 나니 너무 목말라요." },
  { w:"full",              pos:"adj", ko:"배부른",                cat:"food", ex:"I'm too ___ for dessert.",                             exKo:"배가 너무 불러서 디저트는 못 먹겠어요." },
  { w:"taste",             pos:"v",   ko:"맛보다",                cat:"food", ex:"Let me ___ it first.",                                 exKo:"먼저 맛 좀 볼게요." },
  { w:"try",               pos:"v",   ko:"먹어 보다, 해 보다",     cat:"food", ex:"You should ___ the local seafood.",                    exKo:"현지 해산물을 꼭 먹어 보세요." },
  { w:"serve",             pos:"v",   ko:"(음식을) 내다, 팔다",    cat:"food", ex:"Do they ___ breakfast this early?",                    exKo:"이렇게 이른 시간에도 아침을 파나요?" },
  { w:"sold out",          pos:"phr", ko:"다 팔린",               cat:"food", ex:"Sorry, the fish is ___ for today.",                    exKo:"죄송해요, 오늘 생선은 다 팔렸어요." },

  /* ===== 쇼핑 ===== */
  { w:"try on",            pos:"phr", ko:"입어 보다, 신어 보다",   cat:"shop", ex:"Can I ___ this jacket?",                               exKo:"이 재킷 입어 봐도 될까요?" },
  { w:"fitting room",      pos:"n",   ko:"탈의실",                cat:"shop", ex:"The ___ is right behind you.",                         exKo:"탈의실은 바로 뒤에 있어요." },
  { w:"size",              pos:"n",   ko:"치수, 사이즈",           cat:"shop", ex:"Do you have this in my ___ ?",                         exKo:"이거 제 사이즈로 있나요?" },
  { w:"receipt",           pos:"n",   ko:"영수증",                cat:"shop", ex:"Keep the ___ in case you want a refund.",              exKo:"환불할 수도 있으니 영수증을 보관하세요." },
  { w:"refund",            pos:"n",   ko:"환불",                  cat:"shop", ex:"Can I get a ___ if it doesn't fit?",                   exKo:"안 맞으면 환불받을 수 있나요?" },
  { w:"exchange",          pos:"v",   ko:"교환하다",              cat:"shop", ex:"Could I ___ this for another color?",                  exKo:"이거 다른 색으로 교환할 수 있을까요?" },
  { w:"discount",          pos:"n",   ko:"할인",                  cat:"shop", ex:"Is there any ___ if I buy two?",                       exKo:"두 개 사면 할인이 되나요?" },
  { w:"on sale",           pos:"phr", ko:"할인 중인",             cat:"shop", ex:"Everything in this section is ___ .",                  exKo:"이쪽 물건은 전부 할인 중이에요." },
  { w:"bargain",           pos:"n",   ko:"싸게 잘 산 물건",        cat:"shop", ex:"Twenty dollars for this jacket is a real ___ .",       exKo:"이 재킷이 20달러면 정말 잘 산 거예요." },
  { w:"afford",            pos:"v",   ko:"~할 여유가 되다",        cat:"shop", ex:"I can't ___ that one — it's too expensive.",           exKo:"그건 너무 비싸서 못 사겠어요." },
  { w:"cash",              pos:"n",   ko:"현금",                  cat:"shop", ex:"Do you take cards, or is it ___ only?",                exKo:"카드 되나요, 아니면 현금만인가요?" },
  { w:"change",            pos:"n",   ko:"거스름돈, 잔돈",         cat:"shop", ex:"You gave me the wrong ___ .",                          exKo:"거스름돈을 잘못 주셨어요." },
  { w:"souvenir",          pos:"n",   ko:"기념품",                cat:"shop", ex:"I want to buy a small ___ for my brother.",            exKo:"동생에게 줄 작은 기념품을 사고 싶어요." },
  { w:"wrap",              pos:"v",   ko:"포장하다",              cat:"shop", ex:"Could you ___ this as a gift?",                        exKo:"이거 선물용으로 포장해 주시겠어요?" },
  { w:"browse",            pos:"v",   ko:"둘러보다",              cat:"shop", ex:"I'm just here to ___ , thanks.",                       exKo:"그냥 둘러보는 중이에요, 감사합니다." },

  /* ===== 관광 · 액티비티 ===== */
  { w:"look around",       pos:"phr", ko:"여기저기 둘러보다",       cat:"see",  ex:"We just want to ___ for a bit.",                       exKo:"저희는 잠깐 둘러보려고요." },
  { w:"get in",            pos:"phr", ko:"입장하다, 들어가다",      cat:"see",  ex:"How much is it to ___ ?",                              exKo:"입장료가 얼마예요?",           tip:"매표소에서 admission fee보다 이렇게 묻는 게 자연스러움." },
  { w:"guided tour",       pos:"n",   ko:"가이드 동행 투어",       cat:"see",  ex:"Is there a ___ in English?",                           exKo:"영어로 진행하는 가이드 투어가 있나요?" },
  { w:"landmark",          pos:"n",   ko:"랜드마크, 명소",         cat:"see",  ex:"That tower is the city's best-known ___ .",            exKo:"저 탑이 이 도시에서 가장 유명한 명소예요." },
  { w:"view",              pos:"n",   ko:"전망, 경치",            cat:"see",  ex:"The ___ from the top is amazing.",                     exKo:"꼭대기에서 보는 전망이 정말 좋아요." },
  { w:"crowd",             pos:"n",   ko:"인파",                  cat:"see",  ex:"Let's go early to avoid the ___ .",                    exKo:"사람 많은 걸 피하려면 일찍 갑시다." },
  { w:"worth",             pos:"adj", ko:"~할 만한 가치가 있는",   cat:"see",  ex:"Is the museum ___ visiting?",                          exKo:"그 박물관 가볼 만한가요?" },
  { w:"book in advance",   pos:"phr", ko:"미리 예약하다",          cat:"see",  ex:"You should ___ for the tour.",                         exKo:"그 투어는 미리 예약하셔야 해요." },
  { w:"closed",            pos:"adj", ko:"문을 닫은",             cat:"see",  ex:"The gallery is ___ on Mondays.",                       exKo:"그 갤러리는 월요일에 문을 닫아요." },
  { w:"spot",              pos:"n",   ko:"장소, 자리",            cat:"see",  ex:"This is a great ___ for photos.",                      exKo:"여기 사진 찍기 정말 좋은 자리예요." },
  { w:"hidden gem",        pos:"n",   ko:"숨은 명소",             cat:"see",  ex:"That little cafe is a real ___ .",                     exKo:"그 작은 카페는 진짜 숨은 명소예요." },
  { w:"local",             pos:"n",   ko:"현지인",                cat:"see",  ex:"Ask a ___ where to eat.",                              exKo:"어디서 먹을지는 현지인에게 물어보세요." },
  { w:"up to",             pos:"phr", ko:"~하며 지내는",           cat:"plan", ex:"What are you ___ tomorrow?",                          exKo:"내일 뭐 해요?",                tip:"What are you up to? = 뭐 해? 안부와 일정 묻기를 겸함." },
  { w:"wander",            pos:"v",   ko:"거닐다, 어슬렁거리다",   cat:"see",  ex:"We like to just ___ around old streets.",              exKo:"우리는 그냥 옛 거리를 거니는 걸 좋아해요." },
  { w:"must-see",          pos:"n",   ko:"꼭 봐야 할 곳",          cat:"see",  ex:"The night market is a ___ in this city.",              exKo:"야시장은 이 도시에서 꼭 가봐야 할 곳이에요." },

  /* ===== 문제 상황 ===== */
  { w:"lost and found",    pos:"n",   ko:"분실물 센터",            cat:"help", ex:"Try the ___ near the entrance.",                       exKo:"입구 쪽 분실물 센터에 가보세요." },
  { w:"missing",           pos:"adj", ko:"없어진, 안 보이는",      cat:"help", ex:"One of my bags is ___ .",                              exKo:"제 가방 하나가 없어졌어요." },
  { w:"stolen",            pos:"adj", ko:"도난당한",              cat:"help", ex:"My wallet was ___ on the subway.",                     exKo:"지하철에서 지갑을 도난당했어요." },
  { w:"report",            pos:"v",   ko:"신고하다",              cat:"help", ex:"I need to ___ a lost passport.",                       exKo:"여권 분실 신고를 해야 해요." },
  { w:"embassy",           pos:"n",   ko:"대사관",                cat:"help", ex:"You should call your ___ right away.",                 exKo:"바로 대사관에 전화하셔야 해요." },
  { w:"emergency",         pos:"n",   ko:"응급 상황",             cat:"help", ex:"In an ___ , dial one-one-two here.",                   exKo:"응급 상황에는 여기서 112를 누르세요." },
  { w:"broken",            pos:"adj", ko:"고장 난",               cat:"help", ex:"The elevator is ___ again.",                           exKo:"엘리베이터가 또 고장 났어요." },
  { w:"leak",              pos:"v",   ko:"새다",                  cat:"help", ex:"The shower seems to ___ .",                            exKo:"샤워기에서 물이 새는 것 같아요." },
  { w:"complain",          pos:"v",   ko:"불평하다, 항의하다",     cat:"help", ex:"I don't want to ___ , but the room is dirty.",         exKo:"불평하고 싶진 않지만 방이 더러워요." },
  { w:"mistake",           pos:"n",   ko:"실수, 착오",            cat:"help", ex:"There might be a ___ on the bill.",                    exKo:"계산서에 착오가 있는 것 같아요." },
  { w:"charge",            pos:"v",   ko:"(요금을) 청구하다",      cat:"help", ex:"They seem to ___ me twice for the same drink.",        exKo:"같은 음료를 두 번 청구한 것 같아요." },
  { w:"delay",             pos:"n",   ko:"지연",                  cat:"help", ex:"There's a two-hour ___ on all trains.",                exKo:"모든 열차가 두 시간씩 지연되고 있어요." },
  { w:"stuck",             pos:"adj", ko:"갇힌, 꼼짝 못 하는",     cat:"help", ex:"We got ___ in the elevator.",                          exKo:"엘리베이터에 갇혔어요." },
  { w:"run out of",        pos:"phr", ko:"~이 다 떨어지다",        cat:"help", ex:"We're about to ___ cash.",                             exKo:"현금이 거의 다 떨어져 가요." },
  { w:"locked out",        pos:"phr", ko:"문이 잠겨 못 들어가는",  cat:"help", ex:"I'm ___ of my room.",                                  exKo:"방문이 잠겨서 못 들어가고 있어요." },
  { w:"work",              pos:"v",   ko:"작동하다",              cat:"help", ex:"The key card doesn't ___ .",                           exKo:"카드키가 작동하지 않아요." },
  { w:"fix",               pos:"v",   ko:"고치다",                cat:"help", ex:"Can someone come and ___ the heater?",                 exKo:"누가 와서 히터 좀 고쳐 주실 수 있나요?" },
  { w:"spare",             pos:"adj", ko:"여분의",                cat:"help", ex:"Do you have a ___ key?",                               exKo:"여분 열쇠가 있나요?" },

  /* ===== 대화 · 스몰토크 ===== */
  { w:"introduce",         pos:"v",   ko:"소개하다",              cat:"talk", ex:"Let me ___ you to my friend.",                         exKo:"제 친구를 소개해 드릴게요." },
  { w:"mind",              pos:"v",   ko:"꺼리다, 신경 쓰다",      cat:"talk", ex:"Would you ___ taking a photo of us?",                  exKo:"저희 사진 좀 찍어 주시겠어요?" },
  { w:"appreciate",        pos:"v",   ko:"고맙게 여기다",          cat:"talk", ex:"I'd really ___ your help.",                            exKo:"도와주시면 정말 감사하겠습니다." },
  { w:"figure out",        pos:"phr", ko:"알아내다, 파악하다",     cat:"talk", ex:"I can't ___ how this ticket machine works.",           exKo:"이 발권기 쓰는 법을 못 알아내겠어요." },
  { w:"look for",          pos:"phr", ko:"찾다",                  cat:"talk", ex:"Could you help me ___ this address?",                  exKo:"이 주소 찾는 것 좀 도와주시겠어요?" },
  { w:"hang out",          pos:"phr", ko:"같이 놀다, 어울리다",    cat:"talk", ex:"Do you want to ___ with us tonight?",                  exKo:"오늘 밤에 저희랑 같이 놀래요?" },
  { w:"get along",         pos:"phr", ko:"잘 지내다",             cat:"talk", ex:"We ___ really well from day one.",                     exKo:"우리는 첫날부터 정말 잘 지냈어요." },
  { w:"small talk",        pos:"n",   ko:"가벼운 잡담",            cat:"talk", ex:"I'm not great at ___ with strangers.",                 exKo:"저는 낯선 사람과 잡담하는 걸 잘 못해요." },
  { w:"accent",            pos:"n",   ko:"억양, 말투",            cat:"talk", ex:"I love your ___ — where's it from?",                   exKo:"억양이 참 좋으시네요. 어디 억양이에요?" },
  { w:"slow down",         pos:"phr", ko:"천천히 하다",           cat:"talk", ex:"Could you ___ a little? I'm still learning.",          exKo:"조금만 천천히 말씀해 주시겠어요? 아직 배우는 중이에요." },
  { w:"repeat",            pos:"v",   ko:"다시 말하다",           cat:"talk", ex:"Sorry, could you ___ that?",                           exKo:"죄송해요, 다시 말씀해 주시겠어요?" },
  { w:"mean",              pos:"v",   ko:"의미하다",              cat:"talk", ex:"What does this word ___ ?",                            exKo:"이 단어가 무슨 뜻인가요?" },
  { w:"sure",              pos:"adj", ko:"확신하는",              cat:"talk", ex:"I'm not ___ , let me check.",                          exKo:"잘 모르겠어요, 확인해 볼게요." },
  { w:"maybe",             pos:"adv", ko:"어쩌면, 아마",          cat:"talk", ex:"We could ___ meet tomorrow.",                          exKo:"어쩌면 내일 만날 수도 있겠네요." },
  { w:"definitely",        pos:"adv", ko:"확실히, 꼭",            cat:"talk", ex:"That's ___ worth a visit.",                            exKo:"거긴 확실히 가볼 만해요." },
  { w:"kind of",           pos:"phr", ko:"좀, 약간",              cat:"talk", ex:"It's ___ far from here.",                              exKo:"여기서 좀 멀어요." },
  { w:"keep in touch",     pos:"phr", ko:"연락하고 지내다",        cat:"talk", ex:"Let's ___ after the trip.",                            exKo:"여행 끝나고도 연락하고 지내요." },
  { w:"catch up",          pos:"phr", ko:"밀린 이야기를 나누다",   cat:"talk", ex:"We should ___ over coffee sometime.",                  exKo:"언제 커피 마시면서 밀린 얘기해요." },

  /* ===== 건강 · 약국 ===== */
  { w:"pharmacy",          pos:"n",   ko:"약국",                  cat:"care", ex:"Is there a ___ open near here?",                       exKo:"근처에 문 연 약국이 있나요?" },
  { w:"painkiller",        pos:"n",   ko:"진통제",                cat:"care", ex:"I need a ___ for my headache.",                        exKo:"두통약이 필요해요." },
  { w:"prescription",      pos:"n",   ko:"처방전",                cat:"care", ex:"You need a ___ for that medicine.",                    exKo:"그 약은 처방전이 있어야 해요." },
  { w:"sore",              pos:"adj", ko:"아픈, 따가운",           cat:"care", ex:"I have a ___ throat and a runny nose.",                exKo:"목이 아프고 콧물이 나요." },
  { w:"fever",             pos:"n",   ko:"열",                    cat:"care", ex:"She's had a ___ since last night.",                    exKo:"그 애가 어젯밤부터 열이 나요." },
  { w:"rest",              pos:"v",   ko:"쉬다",                  cat:"care", ex:"You should ___ for a day before flying.",              exKo:"비행 전에 하루는 쉬는 게 좋겠어요." },
  { w:"hurt",              pos:"v",   ko:"아프다",                cat:"care", ex:"Does it ___ when you walk?",                           exKo:"걸을 때 아프세요?" },
  { w:"dizzy",             pos:"adj", ko:"어지러운",              cat:"care", ex:"I feel a bit ___ from the heat.",                      exKo:"더워서 좀 어지러워요." },
  { w:"food poisoning",    pos:"n",   ko:"식중독",                cat:"care", ex:"I think I got ___ from the street food.",              exKo:"길거리 음식 때문에 식중독에 걸린 것 같아요." },
  { w:"insurance",         pos:"n",   ko:"보험",                  cat:"care", ex:"Does your travel ___ cover this?",                     exKo:"여행자 보험으로 이게 처리되나요?" },
  { w:"clinic",            pos:"n",   ko:"진료소, 의원",           cat:"care", ex:"The hotel called a ___ for me.",                       exKo:"호텔에서 저 대신 병원에 연락해 줬어요." },
  { w:"sunscreen",         pos:"n",   ko:"자외선 차단제",          cat:"care", ex:"Don't forget to put on ___ .",                         exKo:"자외선 차단제 바르는 거 잊지 마세요." },

  /* ===== 일상 ===== */
  { w:"laundry",           pos:"n",   ko:"빨래, 세탁",            cat:"life", ex:"Is there a place to do ___ nearby?",                   exKo:"근처에 빨래할 만한 곳이 있나요?" },
  { w:"charger",           pos:"n",   ko:"충전기",                cat:"life", ex:"I left my phone ___ at the hotel.",                    exKo:"호텔에 휴대폰 충전기를 두고 왔어요." },
  { w:"adapter",           pos:"n",   ko:"(전원) 어댑터",          cat:"life", ex:"You'll need a plug ___ for Europe.",                   exKo:"유럽에서는 플러그 어댑터가 필요해요." },
  { w:"Wi-Fi password",    pos:"n",   ko:"와이파이 비밀번호",      cat:"life", ex:"Could I get the ___ ?",                                exKo:"와이파이 비밀번호를 알 수 있을까요?" },
  { w:"battery",           pos:"n",   ko:"배터리",                cat:"life", ex:"My ___ is almost dead.",                               exKo:"배터리가 거의 다 됐어요." },
  { w:"ATM",               pos:"n",   ko:"현금인출기",             cat:"life", ex:"Is there an ___ inside the station?",                  exKo:"역 안에 현금인출기가 있나요?" },
  { w:"exchange rate",     pos:"n",   ko:"환율",                  cat:"life", ex:"The ___ at the airport is terrible.",                  exKo:"공항 환율은 정말 안 좋아요." },
  { w:"tap",               pos:"v",   ko:"(카드를) 대다",         cat:"life", ex:"Just ___ your card on the reader.",                    exKo:"카드를 단말기에 대기만 하면 돼요." },
  { w:"line",              pos:"n",   ko:"줄",                    cat:"life", ex:"There's a long ___ at the entrance.",                  exKo:"입구에 줄이 길게 서 있어요." },
  { w:"borrow",            pos:"v",   ko:"빌리다",                cat:"life", ex:"Could I ___ your pen for a second?",                   exKo:"펜 잠깐 빌릴 수 있을까요?" },
  { w:"share",             pos:"v",   ko:"함께 쓰다, 나누다",      cat:"life", ex:"We can ___ a taxi to the airport.",                    exKo:"공항까지 택시를 같이 타면 되겠어요." },
  { w:"hurry",             pos:"v",   ko:"서두르다",              cat:"life", ex:"We'd better ___ or we'll miss it.",                    exKo:"서두르지 않으면 놓치겠어요." },
  { w:"on time",           pos:"phr", ko:"제시간에",              cat:"life", ex:"The bus was right ___ for once.",                      exKo:"버스가 웬일로 정확히 제시간에 왔어요." },
  { w:"take your time",    pos:"phr", ko:"천천히 하세요",          cat:"life", ex:"She told me to ___ .",                                 exKo:"그가 저에게 천천히 하라고 했어요." },
  { w:"run late",          pos:"phr", ko:"늦어지다",              cat:"life", ex:"Sorry, I'm going to ___ by ten minutes.",              exKo:"죄송해요, 10분 정도 늦을 것 같아요." },
  { w:"drop by",           pos:"phr", ko:"잠깐 들르다",           cat:"life", ex:"We can ___ the market on the way.",                    exKo:"가는 길에 시장에 잠깐 들러도 돼요." },

  /* ===== 집 · 집안일 ===== */
  { w:"do the dishes",     pos:"phr", ko:"설거지하다",            cat:"home", ex:"I'll ___ if you cook.",                                exKo:"네가 요리하면 내가 설거지할게." },
  { w:"take out the trash",pos:"phr", ko:"쓰레기를 내다 버리다",   cat:"home", ex:"Don't forget to ___ tonight.",                         exKo:"오늘 밤에 쓰레기 버리는 거 잊지 마." },
  { w:"tidy up",           pos:"phr", ko:"정리정돈하다",           cat:"home", ex:"Let's ___ before the guests arrive.",                  exKo:"손님 오기 전에 좀 치우자." },
  { w:"vacuum",            pos:"v",   ko:"청소기를 돌리다",        cat:"home", ex:"I need to ___ the living room.",                       exKo:"거실에 청소기를 돌려야 해." },
  { w:"fold",              pos:"v",   ko:"(빨래를) 개다",         cat:"home", ex:"Could you ___ the towels?",                            exKo:"수건 좀 개 줄래?" },
  { w:"chore",             pos:"n",   ko:"집안일",                cat:"home", ex:"Everyone in the house has one ___ a day.",             exKo:"우리 집은 각자 하루에 집안일 하나씩 해." },
  { w:"sink",              pos:"n",   ko:"싱크대",                cat:"home", ex:"The dishes are piled up in the ___ .",                 exKo:"싱크대에 설거지가 쌓여 있어." },
  { w:"faucet",            pos:"n",   ko:"수도꼭지",              cat:"home", ex:"The ___ in the bathroom keeps dripping.",             exKo:"화장실 수도꼭지에서 계속 물이 떨어져." },
  { w:"plug in",           pos:"phr", ko:"플러그를 꽂다",          cat:"home", ex:"Did you ___ the vacuum?",                              exKo:"청소기 플러그 꽂았어?" },
  { w:"throw away",        pos:"phr", ko:"버리다",                cat:"home", ex:"You can ___ that old box.",                            exKo:"저 낡은 상자는 버려도 돼." },
  { w:"put away",          pos:"phr", ko:"제자리에 치우다",        cat:"home", ex:"Please ___ your toys before dinner.",                  exKo:"저녁 먹기 전에 장난감 좀 치워." },
  { w:"messy",             pos:"adj", ko:"어질러진",              cat:"home", ex:"Sorry, the place is a bit ___ .",                      exKo:"미안, 집이 좀 어질러져 있어." },
  { w:"rent",              pos:"n",   ko:"집세, 월세",            cat:"home", ex:"We pay ___ on the first of the month.",                exKo:"우리는 매달 1일에 월세를 내." },
  { w:"move in",           pos:"phr", ko:"이사 들어오다",          cat:"home", ex:"They ___ next week.",                                  exKo:"그들은 다음 주에 이사 와." },
  { w:"water",             pos:"v",   ko:"(식물에) 물을 주다",     cat:"home", ex:"Could you ___ the plants while we're away?",           exKo:"우리 없는 동안 화분에 물 좀 줄래?" },
  { w:"make the bed",      pos:"phr", ko:"잠자리를 정돈하다",      cat:"home", ex:"The kids ___ every morning now.",                      exKo:"애들이 요즘 아침마다 이불을 정리해." },

  /* ===== 전화 · 연락 ===== */
  { w:"call back",         pos:"phr", ko:"다시 전화하다",          cat:"call", ex:"I'll ___ in five minutes.",                            exKo:"5분 뒤에 다시 전화할게요." },
  { w:"hang up",           pos:"phr", ko:"전화를 끊다",           cat:"call", ex:"Don't ___ yet, I have one more thing.",                exKo:"아직 끊지 마, 하나만 더 있어." },
  { w:"hold on",           pos:"phr", ko:"잠깐 기다리다",          cat:"call", ex:"Could you ___ a second?",                              exKo:"잠깐만 기다려 주시겠어요?" },
  { w:"text",              pos:"v",   ko:"문자를 보내다",          cat:"call", ex:"Just ___ me when you get there.",                      exKo:"도착하면 문자만 보내 줘." },
  { w:"reach",             pos:"v",   ko:"연락이 닿다",           cat:"call", ex:"What's the best way to ___ you?",                      exKo:"연락드리기 가장 좋은 방법이 뭔가요?" },
  { w:"voicemail",         pos:"n",   ko:"음성 메시지",           cat:"call", ex:"Leave a ___ and I'll get back to you.",                exKo:"음성 메시지 남겨 주시면 다시 연락드릴게요." },
  { w:"break up",          pos:"phr", ko:"(통화가) 끊기다",       cat:"call", ex:"You're starting to ___ — can you hear me?",            exKo:"소리가 끊기기 시작해요. 제 말 들리세요?" },
  { w:"mute",              pos:"v",   ko:"음소거하다",            cat:"call", ex:"You might want to ___ your mic.",                      exKo:"마이크를 음소거하시는 게 좋겠어요." },
  { w:"on speaker",        pos:"phr", ko:"스피커폰으로",           cat:"call", ex:"I'll put you ___ so everyone can hear.",               exKo:"다 들을 수 있게 스피커폰으로 할게요." },
  { w:"get through",       pos:"phr", ko:"(전화가) 연결되다",     cat:"call", ex:"I couldn't ___ to them all morning.",                  exKo:"오전 내내 그쪽에 전화 연결이 안 됐어요." },
  { w:"missed call",       pos:"n",   ko:"부재중 전화",           cat:"call", ex:"I saw your ___ and called right back.",                exKo:"부재중 전화 보고 바로 다시 걸었어요." },
  { w:"reply",             pos:"v",   ko:"답장하다",              cat:"call", ex:"Sorry, I forgot to ___ to your message.",              exKo:"미안, 메시지에 답장하는 걸 깜빡했어." },
  { w:"spam",              pos:"n",   ko:"스팸",                  cat:"call", ex:"That number is probably ___ .",                        exKo:"그 번호는 아마 스팸일 거예요." },

  /* ===== 은행 · 관공서 · 볼일 ===== */
  { w:"run errands",       pos:"phr", ko:"볼일을 보러 다니다",     cat:"task", ex:"I have to ___ this afternoon.",                        exKo:"오후에 볼일 좀 보러 다녀야 해." },
  { w:"open an account",   pos:"phr", ko:"계좌를 개설하다",        cat:"task", ex:"I'd like to ___ , please.",                            exKo:"계좌를 개설하고 싶습니다." },
  { w:"take out",          pos:"phr", ko:"(돈을) 찾다",           cat:"task", ex:"Can I ___ cash without a card?",                       exKo:"카드 없이 현금을 찾을 수 있나요?", tip:"withdraw는 안내문 말투. 말할 땐 take out." },
  { w:"balance",           pos:"n",   ko:"잔액",                  cat:"task", ex:"Let me check my ___ first.",                           exKo:"먼저 잔액 좀 확인할게요." },
  { w:"fill out",          pos:"phr", ko:"(양식을) 작성하다",     cat:"task", ex:"You'll need to ___ this form.",                        exKo:"이 양식을 작성하셔야 해요." },
  { w:"sign",              pos:"v",   ko:"서명하다",              cat:"task", ex:"Please ___ at the bottom of the page.",                exKo:"페이지 하단에 서명해 주세요." },
  { w:"ID",                pos:"n",   ko:"신분증",                cat:"task", ex:"Do I need to bring my ___ ?",                          exKo:"신분증을 가져가야 하나요?" },
  { w:"appointment",       pos:"n",   ko:"(방문) 예약, 약속",     cat:"task", ex:"I made an ___ for Thursday.",                          exKo:"목요일로 예약을 잡았어요." },
  { w:"take a number",     pos:"phr", ko:"번호표를 뽑다",          cat:"task", ex:"You need to ___ first.",                               exKo:"먼저 번호표를 뽑으셔야 해요." },
  { w:"fee",               pos:"n",   ko:"수수료",                cat:"task", ex:"Is there a ___ for using this machine?",               exKo:"이 기계 쓰는 데 수수료가 있나요?" },
  { w:"due",               pos:"adj", ko:"기한이 된",             cat:"task", ex:"The payment is ___ next Friday.",                      exKo:"납부 기한이 다음 주 금요일이에요." },
  { w:"paperwork",         pos:"n",   ko:"서류 작업",             cat:"task", ex:"There's a lot of ___ to fill in.",                     exKo:"작성할 서류가 많아요." },
  { w:"renew",             pos:"v",   ko:"갱신하다",              cat:"task", ex:"I need to ___ my passport this year.",                 exKo:"올해 여권을 갱신해야 해요." },
  { w:"package",           pos:"n",   ko:"소포",                  cat:"task", ex:"I need to send this ___ to Korea.",                    exKo:"이 소포를 한국으로 보내야 해요." },
  { w:"in person",         pos:"phr", ko:"직접 가서",             cat:"task", ex:"You have to apply ___ .",                              exKo:"직접 가서 신청하셔야 해요." },

  /* ===== 날씨 ===== */
  { w:"forecast",          pos:"n",   ko:"일기예보",              cat:"sky",  ex:"The ___ says rain all weekend.",                       exKo:"일기예보에 주말 내내 비래요." },
  { w:"pouring",           pos:"adj", ko:"비가 억수같이 오는",     cat:"sky",  ex:"It's absolutely ___ outside.",                         exKo:"밖에 비가 억수같이 쏟아지고 있어요." },
  { w:"humid",             pos:"adj", ko:"습한",                  cat:"sky",  ex:"Summer here is really ___ .",                          exKo:"여기 여름은 정말 습해요." },
  { w:"chilly",            pos:"adj", ko:"쌀쌀한",                cat:"sky",  ex:"It gets ___ after sunset.",                            exKo:"해 지고 나면 쌀쌀해져요." },
  { w:"freezing",          pos:"adj", ko:"몹시 추운",             cat:"sky",  ex:"It's ___ in here — can we close the window?",          exKo:"여기 너무 추운데 창문 닫아도 될까요?" },
  { w:"warm up",           pos:"phr", ko:"따뜻해지다",            cat:"sky",  ex:"It should ___ by the afternoon.",                      exKo:"오후에는 따뜻해질 거예요." },
  { w:"clear up",          pos:"phr", ko:"(날씨가) 개다",         cat:"sky",  ex:"The sky will ___ later today.",                        exKo:"오늘 늦게는 하늘이 갤 거예요." },
  { w:"breeze",            pos:"n",   ko:"산들바람",              cat:"sky",  ex:"There's a nice ___ by the river.",                     exKo:"강가에 시원한 바람이 불어요." },
  { w:"umbrella",          pos:"n",   ko:"우산",                  cat:"sky",  ex:"Take an ___ just in case.",                            exKo:"혹시 모르니 우산 챙겨." },
  { w:"shade",             pos:"n",   ko:"그늘",                  cat:"sky",  ex:"Let's sit in the ___ .",                               exKo:"그늘에 앉자." },
  { w:"fine dust",         pos:"n",   ko:"미세먼지",              cat:"sky",  ex:"The ___ level is high today.",                         exKo:"오늘 미세먼지 수치가 높아요." },
  { w:"layer",             pos:"n",   ko:"겹쳐 입는 옷",           cat:"sky",  ex:"Bring a light ___ for the evening.",                   exKo:"저녁에 걸칠 얇은 옷 하나 챙겨." },

  /* ===== 감정 · 컨디션 ===== */
  { w:"exhausted",         pos:"adj", ko:"기진맥진한",            cat:"mood", ex:"I'm ___ after that long day.",                         exKo:"긴 하루를 보내고 나니 완전히 지쳤어요." },
  { w:"annoyed",           pos:"adj", ko:"짜증 난",               cat:"mood", ex:"He looked a bit ___ , didn't he?",                     exKo:"그 사람 좀 짜증 나 보이지 않았어?" },
  { w:"nervous",           pos:"adj", ko:"긴장한",                cat:"mood", ex:"I always get ___ before speaking English.",            exKo:"영어로 말하기 전에는 늘 긴장돼요." },
  { w:"relieved",          pos:"adj", ko:"마음이 놓인",           cat:"mood", ex:"I was so ___ when I found my wallet.",                 exKo:"지갑을 찾고 정말 마음이 놓였어요." },
  { w:"upset",             pos:"adj", ko:"속상한",                cat:"mood", ex:"Don't be ___ — it wasn't your fault.",                 exKo:"속상해하지 마. 네 잘못이 아니야." },
  { w:"excited",           pos:"adj", ko:"신이 난",               cat:"mood", ex:"The kids are ___ about the trip.",                     exKo:"애들이 여행 때문에 신났어요." },
  { w:"bored",             pos:"adj", ko:"지루한",                cat:"mood", ex:"I get ___ waiting in line.",                           exKo:"줄 서서 기다리면 지루해져요." },
  { w:"cheer up",          pos:"phr", ko:"기운이 나다",           cat:"mood", ex:"That song always makes me ___ .",                      exKo:"그 노래를 들으면 늘 기운이 나요." },
  { w:"calm down",         pos:"phr", ko:"진정하다",              cat:"mood", ex:"Take a breath and ___ .",                              exKo:"숨 한번 쉬고 진정해." },
  { w:"feel like",         pos:"phr", ko:"~하고 싶은 기분이다",    cat:"mood", ex:"I don't ___ cooking tonight.",                         exKo:"오늘 밤은 요리하고 싶지 않아." },
  { w:"in a good mood",    pos:"phr", ko:"기분이 좋은",           cat:"mood", ex:"She's ___ today.",                                     exKo:"그 사람 오늘 기분이 좋네요." },
  { w:"stressed out",      pos:"phr", ko:"스트레스에 지친",        cat:"mood", ex:"I've been ___ all week.",                              exKo:"이번 주 내내 스트레스에 지쳐 있었어요." },
  { w:"can't wait",        pos:"phr", ko:"너무 기대되다",          cat:"mood", ex:"I ___ for the weekend.",                               exKo:"주말이 너무 기다려져요.",      tip:"look forward to는 이메일용. 말할 땐 can't wait." },
  { w:"give up",           pos:"phr", ko:"포기하다",              cat:"mood", ex:"Don't ___ so easily.",                                 exKo:"그렇게 쉽게 포기하지 마." },
  { w:"worried",           pos:"adj", ko:"걱정하는",              cat:"mood", ex:"I'm a little ___ about the weather.",                  exKo:"날씨가 좀 걱정돼요." },
  { w:"proud",             pos:"adj", ko:"자랑스러운",            cat:"mood", ex:"I'm so ___ of you.",                                   exKo:"네가 정말 자랑스러워." },

  /* ===== 약속 · 일정 ===== */
  { w:"make it",           pos:"phr", ko:"시간 맞춰 가다",         cat:"plan", ex:"Sorry, I can't ___ tonight.",                          exKo:"미안, 오늘 밤엔 못 갈 것 같아." },
  { w:"reschedule",        pos:"v",   ko:"일정을 다시 잡다",       cat:"plan", ex:"Can we ___ for next week?",                            exKo:"다음 주로 일정을 다시 잡을 수 있을까요?" },
  { w:"show up",           pos:"phr", ko:"나타나다",              cat:"plan", ex:"He didn't ___ until nine.",                            exKo:"그 사람 9시나 돼서야 나타났어요." },
  { w:"up for",            pos:"phr", ko:"~할 마음이 있는",        cat:"plan", ex:"Are you ___ dinner tomorrow?",                         exKo:"내일 저녁 같이 먹을 생각 있어요?" },
  { w:"free",              pos:"adj", ko:"시간이 나는",           cat:"plan", ex:"Are you ___ on Saturday afternoon?",                   exKo:"토요일 오후에 시간 되세요?" },
  { w:"put off",           pos:"phr", ko:"미루다",                cat:"plan", ex:"Let's not ___ it any longer.",                         exKo:"더 이상 미루지 말자." },
  { w:"remind",            pos:"v",   ko:"상기시키다",            cat:"plan", ex:"Could you ___ me tomorrow morning?",                   exKo:"내일 아침에 저한테 좀 알려 주시겠어요?" },
  { w:"on my way",         pos:"phr", ko:"가는 중인",             cat:"plan", ex:"I'm ___ — five more minutes.",                         exKo:"가는 중이야. 5분만 더." },
  { w:"plenty of time",    pos:"phr", ko:"시간이 넉넉한",          cat:"plan", ex:"We have ___ before the movie.",                        exKo:"영화 시작까지 시간 넉넉해요." },
  { w:"last minute",       pos:"phr", ko:"막판의",                cat:"plan", ex:"It was a ___ change of plan.",                         exKo:"막판에 계획이 바뀐 거였어요." },
  { w:"count on",          pos:"phr", ko:"믿고 기대다",           cat:"plan", ex:"You can ___ me.",                                      exKo:"저만 믿으세요." },
  { w:"work out",          pos:"phr", ko:"잘 풀리다",             cat:"plan", ex:"I hope everything will ___ .",                         exKo:"다 잘 풀렸으면 좋겠어요." },
  { w:"schedule",          pos:"v",   ko:"일정을 잡다",           cat:"plan", ex:"Let's ___ it for Friday.",                             exKo:"금요일로 일정을 잡읍시다." },

  /* ===== 장보기 · 요리 ===== */
  { w:"grocery shopping",  pos:"n",   ko:"장보기",                cat:"cook", ex:"I do my ___ on Sundays.",                              exKo:"저는 일요일에 장을 봐요." },
  { w:"grocery store",     pos:"n",   ko:"식료품점",              cat:"cook", ex:"There's a ___ around the corner.",                     exKo:"모퉁이 돌면 식료품점이 있어요." },
  { w:"cart",              pos:"n",   ko:"카트",                  cat:"cook", ex:"Can you grab a ___ ?",                                 exKo:"카트 하나 가져올래?" },
  { w:"aisle",             pos:"n",   ko:"(매장) 통로, 코너",     cat:"cook", ex:"The snacks are in the next ___ .",                     exKo:"과자는 다음 코너에 있어요." },
  { w:"still good",        pos:"phr", ko:"아직 먹어도 되는",       cat:"cook", ex:"Is this milk ___ ?",                                   exKo:"이 우유 아직 괜찮아요?",       tip:"유통기한을 따지기보다 이렇게 묻는 게 훨씬 흔함." },
  { w:"fresh",             pos:"adj", ko:"신선한",                cat:"cook", ex:"These tomatoes look really ___ .",                     exKo:"이 토마토들 정말 신선해 보여요." },
  { w:"ripe",              pos:"adj", ko:"잘 익은",               cat:"cook", ex:"Are these avocados ___ yet?",                          exKo:"이 아보카도 이제 익었나요?" },
  { w:"run to the store",  pos:"phr", ko:"가게에 얼른 다녀오다",   cat:"cook", ex:"I need to ___ for eggs.",                              exKo:"계란 사러 가게에 얼른 다녀와야 해." },
  { w:"ingredient",        pos:"n",   ko:"재료",                  cat:"cook", ex:"We're missing one ___ for the recipe.",                exKo:"이 요리 재료가 하나 빠졌어요." },
  { w:"recipe",            pos:"n",   ko:"조리법, 레시피",         cat:"cook", ex:"This ___ only takes twenty minutes.",                  exKo:"이 레시피는 20분이면 돼요." },
  { w:"chop",              pos:"v",   ko:"썰다",                  cat:"cook", ex:"Could you ___ the onions?",                            exKo:"양파 좀 썰어 줄래?" },
  { w:"boil",              pos:"v",   ko:"끓이다",                cat:"cook", ex:"You need to ___ the water first.",                     exKo:"먼저 물을 끓여야 해요." },
  { w:"defrost",           pos:"v",   ko:"해동하다",              cat:"cook", ex:"Don't forget to ___ the meat.",                        exKo:"고기 해동하는 거 잊지 마." },
  { w:"stir",              pos:"v",   ko:"젓다",                  cat:"cook", ex:"Keep the sauce on low and ___ it.",                    exKo:"소스는 약불에 두고 저어 주세요." },
  { w:"out of stock",      pos:"phr", ko:"품절인",                cat:"cook", ex:"That brand is ___ right now.",                         exKo:"그 브랜드는 지금 품절이에요." },

  /* ===== 육아 · 가족 ===== */
  { w:"babysitter",        pos:"n",   ko:"베이비시터",            cat:"kids", ex:"We found a ___ for Friday night.",                     exKo:"금요일 밤에 봐 줄 시터를 구했어요." },
  { w:"daycare",           pos:"n",   ko:"어린이집",              cat:"kids", ex:"I drop him off at ___ at eight.",                      exKo:"8시에 어린이집에 데려다줘요." },
  { w:"stroller",          pos:"n",   ko:"유모차",                cat:"kids", ex:"Is there room for a ___ on the bus?",                  exKo:"버스에 유모차 실을 자리가 있나요?" },
  { w:"nap",               pos:"n",   ko:"낮잠",                  cat:"kids", ex:"He usually takes a ___ after lunch.",                  exKo:"그 애는 보통 점심 먹고 낮잠을 자요." },
  { w:"diaper",            pos:"n",   ko:"기저귀",                cat:"kids", ex:"Could you change his ___ ?",                           exKo:"기저귀 좀 갈아 줄래?" },
  { w:"playground",        pos:"n",   ko:"놀이터",                cat:"kids", ex:"The kids want to go to the ___ .",                     exKo:"애들이 놀이터에 가고 싶어 해요." },
  { w:"throw a tantrum",   pos:"phr", ko:"떼를 쓰다",             cat:"kids", ex:"He'll ___ if he's tired.",                             exKo:"피곤하면 떼를 쓸 거예요." },
  { w:"behave",            pos:"v",   ko:"얌전히 굴다",           cat:"kids", ex:"Please ___ while we're at the restaurant.",            exKo:"식당에 있는 동안은 얌전히 있어 줘." },
  { w:"grow up",           pos:"phr", ko:"자라다, 크다",          cat:"kids", ex:"They ___ so fast.",                                    exKo:"애들은 정말 빨리 커요." },
  { w:"little one",        pos:"n",   ko:"어린 아이, 막내",        cat:"kids", ex:"The ___ is still napping.",                            exKo:"막내는 아직 낮잠 자고 있어요." },
  { w:"bedtime",           pos:"n",   ko:"잘 시간",               cat:"kids", ex:"It's past their ___ .",                                exKo:"애들 잘 시간이 지났어요." },
  { w:"feed",              pos:"v",   ko:"먹이다",                cat:"kids", ex:"I have to ___ the baby first.",                        exKo:"먼저 아기 밥을 먹여야 해요." },
  { w:"carry",             pos:"v",   ko:"안고 다니다, 들다",      cat:"kids", ex:"He wants me to ___ him everywhere.",                   exKo:"그 애는 어디서든 안아 달라고 해요." },
  { w:"relative",          pos:"n",   ko:"친척",                  cat:"kids", ex:"A ___ of mine lives nearby.",                          exKo:"제 친척 한 분이 근처에 살아요." },
  { w:"take turns",        pos:"phr", ko:"번갈아 가며 하다",       cat:"kids", ex:"We ___ getting up at night.",                          exKo:"우리는 밤에 번갈아 가며 일어나요." },

  /* ===== 인터넷 · 기기 ===== */
  { w:"log in",            pos:"phr", ko:"로그인하다",            cat:"tech", ex:"I can't ___ to my account.",                           exKo:"계정에 로그인이 안 돼요." },
  { w:"sign up",           pos:"phr", ko:"가입하다",              cat:"tech", ex:"You have to ___ first.",                               exKo:"먼저 가입하셔야 해요." },
  { w:"reset",             pos:"v",   ko:"재설정하다",            cat:"tech", ex:"I had to ___ my password.",                            exKo:"비밀번호를 재설정해야 했어요." },
  { w:"update",            pos:"v",   ko:"업데이트하다",           cat:"tech", ex:"You should ___ the app first.",                        exKo:"앱을 먼저 업데이트하세요." },
  { w:"download",          pos:"v",   ko:"내려받다",              cat:"tech", ex:"Let me ___ the map before we go.",                     exKo:"출발 전에 지도를 내려받을게요." },
  { w:"stream",            pos:"v",   ko:"스트리밍으로 보다",      cat:"tech", ex:"We usually ___ movies at home.",                       exKo:"우리는 보통 집에서 영화를 스트리밍으로 봐요." },
  { w:"subscription",      pos:"n",   ko:"구독",                  cat:"tech", ex:"I cancelled my ___ last month.",                       exKo:"지난달에 구독을 해지했어요." },
  { w:"notification",      pos:"n",   ko:"알림",                  cat:"tech", ex:"I got a ___ about the delay.",                         exKo:"지연됐다는 알림을 받았어요." },
  { w:"screenshot",        pos:"n",   ko:"화면 캡처",             cat:"tech", ex:"Send me a ___ of the ticket.",                         exKo:"티켓 화면 캡처해서 보내 줘." },
  { w:"type in",           pos:"phr", ko:"입력하다",              cat:"tech", ex:"Just ___ your email here.",                            exKo:"여기에 이메일만 입력하세요." },
  { w:"sign out",          pos:"phr", ko:"로그아웃하다",           cat:"tech", ex:"Don't forget to ___ on public computers.",             exKo:"공용 컴퓨터에서는 꼭 로그아웃하세요." },
  { w:"back up",           pos:"phr", ko:"백업하다",              cat:"tech", ex:"You should ___ your photos.",                          exKo:"사진은 백업해 두는 게 좋아요." },

  /* ===== 동네 · 이웃 ===== */
  { w:"neighbor",          pos:"n",   ko:"이웃",                  cat:"town", ex:"Our new ___ is really friendly.",                      exKo:"새로 온 이웃이 정말 친절해요." },
  { w:"next door",         pos:"phr", ko:"바로 옆집에",           cat:"town", ex:"She lives ___ .",                                      exKo:"그 사람은 바로 옆집에 살아요." },
  { w:"around the corner", pos:"phr", ko:"바로 근처에",           cat:"town", ex:"The bakery is ___ .",                                  exKo:"빵집은 바로 근처예요." },
  { w:"dry cleaner",       pos:"n",   ko:"세탁소",                cat:"town", ex:"I dropped my coat at the ___ .",                       exKo:"세탁소에 코트를 맡겼어요." },
  { w:"haircut",           pos:"n",   ko:"머리 자르기",            cat:"town", ex:"I need a ___ before the wedding.",                     exKo:"결혼식 전에 머리를 좀 잘라야 해요." },
  { w:"trim",              pos:"n",   ko:"살짝 다듬기",           cat:"town", ex:"Just a ___ , please.",                                 exKo:"살짝만 다듬어 주세요." },
  { w:"gym",               pos:"n",   ko:"헬스장",                cat:"town", ex:"There's a ___ in the basement.",                       exKo:"지하에 헬스장이 있어요." },
  { w:"exercise",          pos:"v",   ko:"운동하다",              cat:"town", ex:"I try to ___ three times a week.",                     exKo:"일주일에 세 번은 운동하려고 해요." },
  { w:"convenience store", pos:"n",   ko:"편의점",                cat:"town", ex:"Grab some water at the ___ .",                         exKo:"편의점에서 물 좀 사 와." },
  { w:"move out",          pos:"phr", ko:"이사 나가다",           cat:"town", ex:"They plan to ___ in March.",                           exKo:"그들은 3월에 이사 나갈 계획이에요." },
  { w:"community center",  pos:"n",   ko:"주민센터, 문화센터",     cat:"town", ex:"Yoga classes are at the ___ .",                        exKo:"요가 수업은 주민센터에서 해요." },
  { w:"run into",          pos:"phr", ko:"우연히 마주치다",        cat:"town", ex:"I always ___ someone I know there.",                   exKo:"거기 가면 늘 아는 사람을 마주쳐요." },

  /* ===== 회화 필수 — 원어민이 하루에도 몇 번씩 쓰는 말 =====
     인사·맞장구처럼 문장 맨 앞에 오는 표현은 따옴표 안에 넣어 빈칸을 만들었다. */
  { w:"How's it going",    pos:"phr", ko:"잘 지내?, 어떻게 지내?",  cat:"say", ex:"He waved and said, \"___ ?\"",                          exKo:"그가 손을 흔들며 “잘 지내?”라고 했어요.", tip:"가장 흔한 안부 인사. 대답은 Good, you? 정도면 충분하고 실제 근황을 말할 필요는 없음." },
  { w:"What's up",         pos:"phr", ko:"뭐 해?, 무슨 일이야?",    cat:"say", ex:"She texted me, \"___ ?\"",                              exKo:"그가 “뭐 해?”라고 문자를 보냈어요.", tip:"아주 친한 사이용. 안부이자 용건 묻기. 처음 만난 사람에겐 쓰지 않음." },
  { w:"no worries",        pos:"phr", ko:"괜찮아요, 신경 쓰지 마세요", cat:"say", ex:"I just said ___ when he apologized.",                exKo:"그가 사과했을 때 저는 그냥 괜찮다고 했어요.", tip:"Sorry에 대한 가장 자연스러운 대답. That's OK보다 훨씬 흔함." },
  { w:"sounds good",       pos:"phr", ko:"좋아요, 그럽시다",        cat:"say", ex:"If seven works for you, ___ .",                         exKo:"7시가 괜찮으시면 그렇게 하죠.", tip:"제안에 동의할 때 쓰는 한마디. 이메일에도 그대로 씀." },
  { w:"that works",        pos:"phr", ko:"그거면 돼요",             cat:"say", ex:"Friday at six? Yeah, ___ for me.",                      exKo:"금요일 6시요? 네, 저는 괜찮아요." },
  { w:"never mind",        pos:"phr", ko:"아니에요, 됐어요",        cat:"say", ex:"Actually, ___ — I found it.",                           exKo:"아, 됐어요. 찾았어요.", tip:"하려던 말을 거둘 때. 짜증 난 말투로 들리지 않게 톤을 부드럽게." },
  { w:"I'm good",          pos:"phr", ko:"저는 괜찮아요 (사양)",     cat:"say", ex:"\"More coffee?\" \"___ , thanks.\"",                    exKo:"“커피 더 드릴까요?” “저는 괜찮아요, 감사합니다.”", tip:"거절할 때 No thanks보다 부드럽고 훨씬 흔함." },
  { w:"go ahead",          pos:"phr", ko:"그러세요, 먼저 하세요",    cat:"say", ex:"\"Can I take this seat?\" \"___ .\"",                    exKo:"“여기 앉아도 될까요?” “그럼요.”" },
  { w:"help yourself",     pos:"phr", ko:"마음껏 드세요",           cat:"say", ex:"The snacks are on the table — ___ .",                   exKo:"간식은 테이블에 있어요. 마음껏 드세요." },
  { w:"take care",         pos:"phr", ko:"잘 지내, 조심히 가",      cat:"say", ex:"We hugged and I said, \"___ .\"",                       exKo:"우리는 포옹했고 저는 “잘 지내”라고 했어요.", tip:"헤어질 때 인사. Goodbye보다 따뜻하고 흔함." },
  { w:"hang on",           pos:"phr", ko:"잠깐만",                 cat:"say", ex:"She said, \"___ , I'll be right there.\"",              exKo:"그가 “잠깐만, 금방 갈게”라고 했어요." },
  { w:"gonna",             pos:"phr", ko:"~할 거야 (going to)",    cat:"say", ex:"I'm ___ grab some coffee.",                             exKo:"커피 좀 사 올게요.", tip:"말할 때는 거의 항상 gonna로 발음. 글로 쓸 땐 going to." },
  { w:"wanna",             pos:"phr", ko:"~하고 싶다 (want to)",   cat:"say", ex:"Do you ___ come with us?",                              exKo:"우리랑 같이 갈래요?", tip:"친구 사이 구어. 격식 있는 자리에서는 want to." },
  { w:"pretty",            pos:"adv", ko:"꽤, 상당히",             cat:"say", ex:"The food was ___ good.",                                exKo:"음식이 꽤 괜찮았어요.", tip:"very보다 훨씬 자주 씀. pretty good은 최고가 아니라 괜찮은 정도." },
  { w:"totally",           pos:"adv", ko:"완전히, 진짜 그래",      cat:"say", ex:"\"Was it worth it?\" \"___ .\"",                        exKo:"“갈 만했어?” “완전.”" },
  { w:"I mean",            pos:"phr", ko:"그러니까 내 말은",        cat:"say", ex:"It's fine — ___ , it's not perfect, but it works.",     exKo:"괜찮아요. 그러니까, 완벽하진 않지만 쓸 만해요.", tip:"말을 고쳐 말하거나 시간을 벌 때. 원어민 대화에 가장 많이 끼는 표현." },
  { w:"you know",          pos:"phr", ko:"있잖아, 알지?",          cat:"say", ex:"It was that place near the park, ___ ?",                exKo:"공원 근처 그 집 있잖아요, 알죠?" },
  { w:"I guess",           pos:"phr", ko:"~인 것 같아 (반쯤 확신)", cat:"say", ex:"We could go tomorrow, ___ .",                          exKo:"내일 가도 될 것 같기도 하고요." },
  { w:"stuff",             pos:"n",   ko:"물건, 것들",             cat:"say", ex:"I need to buy some ___ for the trip.",                  exKo:"여행 갈 때 쓸 것 좀 사야 해요.", tip:"things보다 캐주얼. 일일이 나열하기 귀찮을 때 통째로." },
  { w:"a bunch of",        pos:"phr", ko:"많은, 잔뜩",             cat:"say", ex:"I took ___ photos there.",                              exKo:"거기서 사진을 잔뜩 찍었어요." },
  { w:"a couple of",       pos:"phr", ko:"두어 개의, 몇 개의",      cat:"say", ex:"Give me ___ minutes.",                                  exKo:"몇 분만 주세요." },
  { w:"end up",            pos:"phr", ko:"결국 ~하게 되다",         cat:"say", ex:"We'll probably ___ eating at home.",                    exKo:"결국 집에서 먹게 될 것 같아요.", tip:"계획과 다르게 흘러갔을 때. 원어민이 정말 자주 씀." },
  { w:"turn out",          pos:"phr", ko:"(결과가) ~로 드러나다",   cat:"say", ex:"It might ___ to be cheaper online.",                    exKo:"온라인이 더 쌀 수도 있어요." },
  { w:"about to",          pos:"phr", ko:"막 ~하려는 참인",         cat:"say", ex:"We're ___ leave.",                                      exKo:"저희 막 나가려던 참이에요." },
  { w:"used to",           pos:"phr", ko:"예전에는 ~했다",          cat:"say", ex:"I ___ live near here.",                                 exKo:"저 예전에 이 근처 살았어요.", tip:"지금은 아니라는 뜻이 핵심." },
  { w:"supposed to",       pos:"phr", ko:"~하기로 되어 있다",       cat:"say", ex:"We're ___ meet at seven.",                              exKo:"우리 7시에 만나기로 했잖아요." },
  { w:"would rather",      pos:"phr", ko:"차라리 ~하겠다",          cat:"say", ex:"I ___ stay in tonight.",                                exKo:"오늘 밤은 그냥 집에 있을래요." },
  { w:"might as well",     pos:"phr", ko:"이왕이면 ~하는 게 낫다",  cat:"say", ex:"We're here, so we ___ look around.",                    exKo:"여기까지 왔으니 이왕 둘러보죠." },
  { w:"in case",           pos:"phr", ko:"~할 경우를 대비해",       cat:"say", ex:"Take a jacket ___ it gets cold.",                       exKo:"추워질지 모르니 겉옷 챙겨요." },
  { w:"no big deal",       pos:"phr", ko:"별일 아니야",             cat:"say", ex:"Don't worry, it's ___ .",                               exKo:"걱정 마세요, 별일 아니에요." },
  { w:"grab",              pos:"v",   ko:"얼른 사다, 집어 들다",    cat:"say", ex:"Let's ___ a coffee before the movie.",                  exKo:"영화 보기 전에 커피 한잔 하죠.", tip:"buy·get 대신 캐주얼하게. grab a bite = 간단히 뭐 좀 먹다." },
  { w:"deal with",         pos:"phr", ko:"처리하다, 감당하다",      cat:"say", ex:"I'll ___ it tomorrow.",                                 exKo:"그건 내일 처리할게요." },
  { w:"get rid of",        pos:"phr", ko:"없애다, 처분하다",        cat:"say", ex:"We should ___ this old sofa.",                          exKo:"이 낡은 소파 처분해야겠어요." },
  { w:"put up with",       pos:"phr", ko:"참고 견디다",             cat:"say", ex:"I can't ___ that noise anymore.",                       exKo:"저 소음 더는 못 참겠어요." },
  { w:"come across",       pos:"phr", ko:"우연히 발견하다",         cat:"say", ex:"I might ___ a better price online.",                    exKo:"온라인에서 더 싼 걸 발견할 수도 있어요." },
  { w:"look up",           pos:"phr", ko:"(정보를) 찾아보다",       cat:"say", ex:"Let me ___ the address.",                               exKo:"주소 좀 찾아볼게요." },
  { w:"head out",          pos:"phr", ko:"나서다, 출발하다",        cat:"say", ex:"We should ___ soon.",                                   exKo:"슬슬 나가야겠어요." },
  { w:"call it a day",     pos:"phr", ko:"오늘은 여기까지 하다",     cat:"say", ex:"Let's ___ and go home.",                                exKo:"오늘은 여기까지 하고 집에 갑시다." },
  { w:"hang in there",     pos:"phr", ko:"조금만 더 버텨",          cat:"say", ex:"He told me to ___ .",                                   exKo:"그가 저에게 조금만 더 버티라고 했어요." },
  { w:"it's on me",        pos:"phr", ko:"내가 낼게",              cat:"say", ex:"Put your wallet away, ___ .",                           exKo:"지갑 넣어요, 제가 낼게요." },
  { w:"keep the change",   pos:"phr", ko:"잔돈은 됐어요",           cat:"say", ex:"He handed over the cash and said, \"___ .\"",           exKo:"그가 현금을 건네며 “잔돈은 됐어요”라고 했어요." },
  { w:"I'll pass",         pos:"phr", ko:"저는 됐어요, 사양할게요",  cat:"say", ex:"\"Want dessert?\" \"___ , thanks.\"",                   exKo:"“디저트 드실래요?” “저는 됐어요, 감사합니다.”" },
  { w:"into",              pos:"phr", ko:"~에 푹 빠진",            cat:"say", ex:"I'm really ___ hiking these days.",                     exKo:"요즘 등산에 푹 빠졌어요.", tip:"be into = 취미로 좋아하다. What are you into? = 뭐 좋아해요?" },
  { w:"get it",            pos:"phr", ko:"이해하다, 알아듣다",      cat:"say", ex:"Sorry, I don't ___ .",                                  exKo:"죄송해요, 이해를 못 했어요.", tip:"understand보다 훨씬 캐주얼하고 흔함." },
  { w:"make sense",        pos:"phr", ko:"말이 되다, 이해가 되다",   cat:"say", ex:"That doesn't ___ to me.",                               exKo:"저한테는 그게 말이 안 되는데요." },
  { w:"by the way",        pos:"phr", ko:"그런데, 참",             cat:"say", ex:"Thanks again — ___ , where did you buy that?",          exKo:"다시 한번 고마워요. 그런데 그거 어디서 샀어요?" },
  { w:"anyway",            pos:"adv", ko:"어쨌든, 그건 그렇고",     cat:"say", ex:"It's late — ___ , I should go.",                        exKo:"늦었네요. 어쨌든 저는 가봐야겠어요.", tip:"화제를 돌리거나 대화를 마무리할 때." },
  { w:"all set",           pos:"phr", ko:"준비가 다 된",           cat:"say", ex:"Are you ___ to go?",                                    exKo:"갈 준비 다 되셨어요?", tip:"식당·상점에서 All set? = 다 되셨어요?" },
  { w:"up to you",         pos:"phr", ko:"네가 정해",              cat:"say", ex:"Pizza or noodles? It's ___ .",                          exKo:"피자요, 국수요? 정하세요." },
  { w:"either way",        pos:"phr", ko:"어느 쪽이든",            cat:"say", ex:"I can go or stay — ___ , I'm fine.",                    exKo:"가도 되고 있어도 되고, 어느 쪽이든 괜찮아요." },
  { w:"no way",            pos:"phr", ko:"말도 안 돼",             cat:"say", ex:"\"He walked home?\" \"___ !\"",                         exKo:"“걸어서 집에 갔다고?” “말도 안 돼!”" },
  { w:"way too",           pos:"phr", ko:"너무 지나치게",           cat:"say", ex:"That's ___ expensive.",                                 exKo:"그건 너무 비싸요." },
  { w:"right away",        pos:"phr", ko:"지금 바로",              cat:"say", ex:"I'll do it ___ .",                                      exKo:"지금 바로 할게요." },
  { w:"pretty much",       pos:"phr", ko:"거의 다",                cat:"say", ex:"We're ___ done.",                                       exKo:"거의 다 끝났어요." },
  { w:"or something",      pos:"phr", ko:"~라든가, 뭐 그런 거",     cat:"say", ex:"Let's get pizza ___ .",                                 exKo:"피자나 뭐 그런 거 시키죠." },
  { w:"my bad",            pos:"phr", ko:"내 잘못이야",            cat:"say", ex:"He just said, \"___ ,\" and moved on.",                 exKo:"그는 “내 잘못이야”라고만 하고 넘어갔어요.", tip:"아주 캐주얼. 제대로 사과해야 할 자리에선 I'm sorry." },
  { w:"for real",          pos:"phr", ko:"진짜야?, 진심이야",       cat:"say", ex:"Are you ___ ?",                                         exKo:"진짜예요?" },
  { w:"chill",             pos:"v",   ko:"쉬다, 느긋하게 있다",     cat:"say", ex:"We just want to ___ at home tonight.",                  exKo:"오늘 밤은 그냥 집에서 쉬고 싶어요." },

  /* ===== 회사 · 업무 일상 ===== */
  { w:"day off",           pos:"n",   ko:"쉬는 날, 휴가",          cat:"work", ex:"I'm taking a ___ on Friday.",                          exKo:"금요일에 하루 쉬려고요." },
  { w:"call in sick",      pos:"phr", ko:"아파서 못 간다고 연락하다", cat:"work", ex:"He had to ___ this morning.",                        exKo:"그는 오늘 아침 아파서 못 온다고 연락했어요." },
  { w:"work from home",    pos:"phr", ko:"재택근무하다",            cat:"work", ex:"I usually ___ on Wednesdays.",                         exKo:"저는 보통 수요일에 재택근무해요." },
  { w:"swamped",           pos:"adj", ko:"일에 파묻힌",            cat:"work", ex:"I'm totally ___ this week.",                           exKo:"이번 주는 일에 완전히 파묻혀 있어요.", tip:"very busy를 더 실감 나게. I'm swamped. 한마디면 충분." },
  { w:"heads-up",          pos:"n",   ko:"미리 알려주는 것",        cat:"work", ex:"Thanks for the ___ .",                                 exKo:"미리 알려줘서 고마워요.", tip:"Give me a heads-up = 미리 좀 알려줘." },
  { w:"lunch break",       pos:"n",   ko:"점심시간",               cat:"work", ex:"I'll call you during my ___ .",                        exKo:"점심시간에 전화할게요." },
  { w:"overtime",          pos:"n",   ko:"야근, 초과근무",          cat:"work", ex:"I did a lot of ___ last month.",                       exKo:"지난달에 야근을 많이 했어요." },
  { w:"deadline",          pos:"n",   ko:"마감일",                 cat:"work", ex:"The ___ is Friday at noon.",                           exKo:"마감은 금요일 정오예요." },
  { w:"meeting",           pos:"n",   ko:"회의",                   cat:"work", ex:"I'm in a ___ right now.",                              exKo:"지금 회의 중이에요." },
  { w:"commute",           pos:"n",   ko:"통근, 출퇴근길",          cat:"work", ex:"My ___ takes about an hour.",                          exKo:"출퇴근에 한 시간쯤 걸려요." },
  { w:"coworker",          pos:"n",   ko:"직장 동료",              cat:"work", ex:"A ___ of mine recommended it.",                        exKo:"제 직장 동료가 추천해 줬어요." },
  { w:"boss",              pos:"n",   ko:"상사",                   cat:"work", ex:"I have to ask my ___ first.",                          exKo:"먼저 상사에게 물어봐야 해요." },
  { w:"get off work",      pos:"phr", ko:"퇴근하다",               cat:"work", ex:"What time do you ___ ?",                               exKo:"몇 시에 퇴근해요?" },
  { w:"take a break",      pos:"phr", ko:"잠깐 쉬다",              cat:"work", ex:"Let's ___ for ten minutes.",                           exKo:"10분만 쉬었다 하죠." },
  { w:"keep me posted",    pos:"phr", ko:"계속 알려줘",            cat:"work", ex:"Sounds good — ___ .",                                  exKo:"좋아요. 계속 알려주세요." },
  { w:"follow up",         pos:"phr", ko:"후속으로 챙기다",         cat:"work", ex:"I'll ___ with them tomorrow.",                         exKo:"내일 그쪽에 다시 확인해 볼게요." },
  { w:"check with",        pos:"phr", ko:"~에게 확인해 보다",       cat:"work", ex:"Let me ___ my manager first.",                         exKo:"먼저 매니저에게 확인해 볼게요." },
  { w:"busy",              pos:"adj", ko:"바쁜",                   cat:"work", ex:"Are you ___ right now?",                               exKo:"지금 바쁘세요?" },

  /* ===== 의견 말하기 · 대화 이어가기 ===== */
  { w:"I think",           pos:"phr", ko:"내 생각엔",              cat:"view", ex:"Honestly, ___ it's too expensive.",                    exKo:"솔직히 제 생각엔 너무 비싼 것 같아요." },
  { w:"it depends",        pos:"phr", ko:"상황에 따라 달라요",      cat:"view", ex:"\"Is it cheaper?\" \"___ .\"",                         exKo:"“그게 더 싸요?” “상황에 따라 달라요.”" },
  { w:"to be honest",      pos:"phr", ko:"솔직히 말하면",           cat:"view", ex:"I liked the food, but ___ , the service was slow.",    exKo:"음식은 좋았는데 솔직히 서비스가 느렸어요." },
  { w:"personally",        pos:"adv", ko:"개인적으로는",            cat:"view", ex:"I know it's popular, but ___ , I prefer the other one.", exKo:"인기 있는 건 아는데 개인적으로는 다른 게 더 좋아요." },
  { w:"agree",             pos:"v",   ko:"동의하다",               cat:"view", ex:"I totally ___ with you.",                              exKo:"완전히 동감이에요." },
  { w:"not really",        pos:"phr", ko:"딱히 그렇진 않아요",      cat:"view", ex:"\"Do you like it?\" \"___ .\"",                        exKo:"“마음에 들어요?” “딱히요.”", tip:"No라고 딱 자르기 뭐할 때 부드럽게 부정하는 말." },
  { w:"on the other hand", pos:"phr", ko:"반면에",                 cat:"view", ex:"It's cheap; ___ , it's pretty far.",                   exKo:"싸긴 한데 반면에 꽤 멀어요." },
  { w:"the thing is",      pos:"phr", ko:"문제는 말이죠",           cat:"view", ex:"I want to go, but ___ , I'm working that day.",        exKo:"가고 싶은데 문제는 그날 일을 해요." },
  { w:"point",             pos:"n",   ko:"요점, 일리 있는 말",      cat:"view", ex:"That's a good ___ .",                                  exKo:"그거 일리 있는 말이네요." },
  { w:"how come",          pos:"phr", ko:"어째서, 왜",             cat:"view", ex:"I wonder ___ you didn't call.",                        exKo:"왜 전화 안 했는지 궁금하네요.", tip:"why보다 캐주얼. 뒤에 평서문 어순이 온다 — how come you didn't." },
  { w:"no idea",           pos:"phr", ko:"전혀 모르겠어요",         cat:"view", ex:"I have ___ where it is.",                              exKo:"그게 어디 있는지 전혀 모르겠어요." },
  { w:"sounds like",       pos:"phr", ko:"~인 것 같네요",          cat:"view", ex:"That ___ a good plan.",                                exKo:"그거 좋은 계획인 것 같네요." },
  { w:"make up your mind", pos:"phr", ko:"마음을 정하다",           cat:"view", ex:"Take your time and ___ .",                             exKo:"천천히 생각하고 마음을 정하세요." },
  { w:"as far as I know",  pos:"phr", ko:"내가 알기로는",           cat:"view", ex:"It opens at nine, ___ .",                              exKo:"제가 알기로는 9시에 열어요." },
  { w:"that's why",        pos:"phr", ko:"그래서 ~한 거예요",       cat:"view", ex:"It rained — ___ we stayed in.",                        exKo:"비가 왔어요. 그래서 집에 있었죠." },

  /* ===== 배달 · 온라인 쇼핑 ===== */
  { w:"delivery",          pos:"n",   ko:"배달, 배송",             cat:"deli", ex:"The ___ should arrive by six.",                        exKo:"배송은 6시까지 올 거예요." },
  { w:"place an order",    pos:"phr", ko:"주문을 넣다",            cat:"deli", ex:"I'll ___ right now.",                                  exKo:"지금 바로 주문 넣을게요." },
  { w:"free shipping",     pos:"n",   ko:"무료 배송",              cat:"deli", ex:"They offer ___ over fifty dollars.",                   exKo:"50달러 넘으면 무료 배송이에요." },
  { w:"track",             pos:"v",   ko:"(배송을) 조회하다",       cat:"deli", ex:"You can ___ your package online.",                     exKo:"온라인에서 배송 조회할 수 있어요." },
  { w:"out for delivery",  pos:"phr", ko:"배송 출발한",            cat:"deli", ex:"It says the box is ___ .",                             exKo:"택배가 배송 출발했다고 나오네요." },
  { w:"return",            pos:"v",   ko:"반품하다",               cat:"deli", ex:"I need to ___ these shoes.",                           exKo:"이 신발 반품해야 해요." },
  { w:"in stock",          pos:"adj", ko:"재고가 있는",            cat:"deli", ex:"Is this ___ in blue?",                                 exKo:"이거 파란색 재고 있나요?" },
  { w:"doorstep",          pos:"n",   ko:"문 앞",                  cat:"deli", ex:"They left it on my ___ .",                             exKo:"문 앞에 두고 갔어요." },
  { w:"courier",           pos:"n",   ko:"택배 기사",              cat:"deli", ex:"The ___ called me twice.",                             exKo:"택배 기사님이 두 번 전화했어요." },
  { w:"order number",      pos:"n",   ko:"주문번호",               cat:"deli", ex:"Can you tell me your ___ ?",                           exKo:"주문번호를 알려주시겠어요?" },
  { w:"arrive",            pos:"v",   ko:"도착하다",               cat:"deli", ex:"When will it ___ ?",                                   exKo:"언제 도착할까요?" },
  { w:"review",            pos:"n",   ko:"후기, 리뷰",             cat:"deli", ex:"The ___ said it runs small.",                          exKo:"후기에 작게 나온다고 돼 있었어요." },
  { w:"add to cart",       pos:"phr", ko:"장바구니에 담다",         cat:"deli", ex:"Just ___ and pay later.",                              exKo:"일단 장바구니에 담고 나중에 결제해요." },
  { w:"deal",              pos:"n",   ko:"특가, 좋은 조건",         cat:"deli", ex:"That's a really good ___ .",                           exKo:"그거 진짜 잘 산 거예요." },

  /* ===== 취미 · 주말 ===== */
  { w:"binge-watch",       pos:"v",   ko:"몰아 보다",              cat:"fun",  ex:"We ___ the whole season last weekend.",                exKo:"지난 주말에 시즌 전체를 몰아 봤어요." },
  { w:"go for a walk",     pos:"phr", ko:"산책하러 가다",           cat:"fun",  ex:"Let's ___ after dinner.",                              exKo:"저녁 먹고 산책하러 가요." },
  { w:"catch a movie",     pos:"phr", ko:"영화 한 편 보다",         cat:"fun",  ex:"Do you want to ___ tonight?",                          exKo:"오늘 밤에 영화 한 편 볼래요?" },
  { w:"hobby",             pos:"n",   ko:"취미",                   cat:"fun",  ex:"Cooking is my new ___ .",                              exKo:"요리가 제 새 취미예요." },
  { w:"board game",        pos:"n",   ko:"보드게임",               cat:"fun",  ex:"We played a ___ with the kids.",                       exKo:"애들이랑 보드게임 했어요." },
  { w:"hiking",            pos:"n",   ko:"등산, 하이킹",           cat:"fun",  ex:"We're going ___ on Saturday.",                         exKo:"토요일에 등산 가요." },
  { w:"playlist",          pos:"n",   ko:"재생목록",               cat:"fun",  ex:"She made a ___ for the drive.",                        exKo:"드라이브용 재생목록을 만들었어요." },
  { w:"weekend plans",     pos:"n",   ko:"주말 계획",              cat:"fun",  ex:"Do you have any ___ ?",                                exKo:"주말에 무슨 계획 있어요?" },
  { w:"sleep in",          pos:"phr", ko:"늦잠 자다",              cat:"fun",  ex:"I like to ___ on Sundays.",                            exKo:"일요일엔 늦잠 자는 걸 좋아해요." },
  { w:"day trip",          pos:"n",   ko:"당일치기 여행",           cat:"fun",  ex:"We took a ___ to the coast.",                          exKo:"바닷가로 당일치기 다녀왔어요." },
  { w:"take up",           pos:"phr", ko:"(취미를) 시작하다",       cat:"fun",  ex:"I want to ___ tennis.",                                exKo:"테니스를 시작해 보고 싶어요." },
  { w:"good at",           pos:"phr", ko:"~를 잘하는",             cat:"fun",  ex:"He's really ___ drawing.",                             exKo:"그는 그림을 정말 잘 그려요." },
  { w:"show",              pos:"n",   ko:"방송 프로그램, 공연",     cat:"fun",  ex:"That ___ is really funny.",                            exKo:"그 프로그램 진짜 웃겨요." },
  { w:"camping",           pos:"n",   ko:"캠핑",                   cat:"fun",  ex:"We're going ___ next month.",                          exKo:"다음 달에 캠핑 가요." }
];

const CATEGORY_LABEL = {
  say:"회화 필수",
  // 여행
  air:"공항·기내", stay:"숙소", move:"교통·길찾기", food:"식당·카페", shop:"쇼핑",
  see:"관광", help:"문제상황", care:"건강·약국",
  // 일상
  home:"집·집안일", cook:"장보기·요리", kids:"육아·가족", call:"전화·연락",
  task:"은행·관공서", town:"동네·이웃", tech:"인터넷·기기", deli:"배달·온라인쇼핑",
  work:"회사·업무", view:"의견 말하기", fun:"취미·주말",
  sky:"날씨", mood:"감정·컨디션", plan:"약속·일정", talk:"대화", life:"일상 기타"
};
const POS_LABEL = { v:"동사", n:"명사", adj:"형용사", adv:"부사", phr:"표현" };

// 시작 화면 상황 고르기용 — 아이콘 + 그룹. 나열 순서가 화면 노출 순서.
const CATEGORY_META = {
  say:  { icon:"💬", group:"basic" },
  air:  { icon:"✈️", group:"travel" }, stay:{ icon:"🏨", group:"travel" },
  move: { icon:"🚌", group:"travel" }, food:{ icon:"🍽️", group:"travel" },
  shop: { icon:"🛍️", group:"travel" }, see:{ icon:"📸", group:"travel" },
  help: { icon:"🆘", group:"travel" }, care:{ icon:"💊", group:"travel" },
  work: { icon:"💼", group:"daily" }, view:{ icon:"🗣️", group:"daily" },
  home: { icon:"🧹", group:"daily" }, cook:{ icon:"🛒", group:"daily" },
  kids: { icon:"👶", group:"daily" }, call:{ icon:"📞", group:"daily" },
  task: { icon:"🏦", group:"daily" }, town:{ icon:"🏘️", group:"daily" },
  tech: { icon:"📱", group:"daily" }, deli:{ icon:"📦", group:"daily" },
  fun:  { icon:"🎮", group:"daily" }, sky:{ icon:"🌤️", group:"daily" },
  mood: { icon:"🙂", group:"daily" }, plan:{ icon:"📅", group:"daily" },
  talk: { icon:"👋", group:"daily" }, life:{ icon:"✨", group:"daily" }
};
const GROUP_LABEL = { basic:"기초 회화", travel:"여행", daily:"일상생활" };
